<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
class C_DonHangViewDetail extends ViewDetail
{
    public function display()
    {
        $madh=$this->bean->id;
        global $db;
        $sql="Select c_sanpham.id as masanpham, c_sanpham.name as tensanpham, c_sanpham.gia as giasanpham, soluong
            from c_donhang
            inner join c_chitietdh on c_donhang.id = c_chitietdh.donhang_id
            inner join c_sanpham on c_sanpham.id=c_chitietdh.sanpham_id
            where c_donhang.deleted=0 and c_chitietdh.deleted=0 and c_sanpham.deleted=0 and c_donhang.id='$madh'";
        $result = $db->query($sql);
        $index=0;
        while($row=$db->fetchByAssoc($result)) {
            $options[$index]['name'] = $row['tensanpham'];
            $options[$index]['soluong'] = $row['soluong'];
            $options[$index]['gia'] = $row['giasanpham'];
            $index++;
        }


        $this->ss->assign("options",$options);
        $this->ss->assign("discount",$this->bean->discount);
        $this->ss->assign("disamount",$this->bean->disamount);

        # from id don hang que
        //print($options);
        parent::display(); // TODO: Change the autogenerated stub
    }
}